DROP TABLE IF EXISTS `#__complaints`;
DROP TABLE IF EXISTS `#__complaint_message_ids`;
DROP TABLE IF EXISTS `#__complaint_notifications`;
DROP TABLE IF EXISTS `#__complaint_pictures`;
DROP TABLE IF EXISTS `#__complaint_contracts`;
DROP TABLE IF EXISTS `#__complaint_sections`;
DROP TABLE IF EXISTS `#__complaint_message_queue`
DROP TABLE IF EXISTS `#__complaint_areas`;
DROP TABLE IF EXISTS `#__complaint_support_groups`;
DROP TABLE IF EXISTS `#__complaint_support_groups_users_map`;